---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-test-io-elisii-com-v1-mycrd
  failurePolicy: Fail
  name: mmycrd.kb.io
  rules:
  - apiGroups:
    - test.io.elisii.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mycrds
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-test-io-elisii-com-v1-mycrd
  failurePolicy: Fail
  name: vmycrd.kb.io
  rules:
  - apiGroups:
    - test.io.elisii.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mycrds
  sideEffects: None
