---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - test.io.elisii.com
  resources:
  - mycrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.io.elisii.com
  resources:
  - mycrds/finalizers
  verbs:
  - update
- apiGroups:
  - test.io.elisii.com
  resources:
  - mycrds/status
  verbs:
  - get
  - patch
  - update
