apiVersion: v1
kind: Namespace
metadata:
  name: dev
---      
apiVersion: test.io.elisii.com/v1
kind: MyCrd
metadata:
  labels:
    app.kubernetes.io/name: mycrd
    app.kubernetes.io/instance: mycrd-sample
    app.kubernetes.io/part-of: k8s-test
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-test
  name: mycrd-sample
  namespace: dev
spec:
  cidr: 192.168.0.1/24
